# MediaWiki with MariaDB
#
# Access via "http://localhost:80"
#   (or "http://$(docker-machine ip):80" if using docker-machine)
version: '3'
services:
  mediawiki:
    image: mediawiki:1.41.0
    restart: always
    ports:
      - "8080:80"
    links:
      - database
    volumes:
#      - files:/var/www/html/files
      - images:/var/www/html/images
      # After initial setup, download LocalSettings.php to the same directory as
      # this yaml and uncomment the following line and use compose to restart
      # the mediawiki service
      - ./LocalSettings.php:/var/www/html/LocalSettings.php
  # This key also defines the name of the database host used during setup instead of the default "localhost"
  database:
    image: mariadb:11.3.2
    restart: always
    environment:
      # @see https://phabricator.wikimedia.org/source/mediawiki/browse/master/includes/DefaultSettings.php
      MYSQL_DATABASE: my_wiki
      MYSQL_USER: wikiuser
      MYSQL_PASSWORD: example
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db:/var/lib/mysql

volumes:
  images:
  db: